name: Vagrant
on: [ push ]
jobs:
  libvirt:
    runs-on: ubuntu-20.04
    env:
      VAGRANT_DEFAULT_PROVIDER: libvirt
    steps:

      - name: Install libvirt
        run: |
          sudo apt install qemu-kvm libvirt-daemon-system
          sudo adduser $USER libvirt

      - name: Check KVM
        run: sudo kvm-ok

      - name: Install vagrant
        run: |
          set -o pipefail
          echo "deb [arch=amd64] https://apt.releases.hashicorp.com focal main" \
          | sudo tee -a /etc/apt/sources.list.d/hashicorp.list
          curl -fsSL https://apt.releases.hashicorp.com/gpg \
          | sudo apt-key add -
          sudo apt-get install -y vagrant

      - name: Cache vagrant boxes
        uses: actions/cache@v2
        env:
          cache-name: vagrant_boxes
        with:
          path: ~/.vagrant.d/boxes/generic-VAGRANTSLASH-debian10
          key: ${{ runner.os }}-${{ env.cache-name }}-debian10
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      - name: Add box generic/debian10
        run: vagrant box add --provider=libvirt --box-version 3.1.6 generic/debian10

      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Run vagrant
        run: vagrant up
        working-directory: source

      - name: Stop vagrant
        run: vagrant destroy --force
        working-directory: source
