name: Vagrant
on: [ push ]
jobs:
  libvirt:
    runs-on: ubuntu-20.04
    env:
      VAGRANT_DEFAULT_PROVIDER: libvirt
    steps:

      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Cache vagrant boxes
        uses: actions/cache@v2
        env:
          cache-name: vagrant_boxes
        with:
          path: ~/.vagrant.d/boxes/generic-VAGRANTSLASH-debian10
          key: ${{ runner.os }}-${{ env.cache-name }}-debian10

      - name: User info
        run: |
          set -x
          env
          id
          pwd
          echo $HOME

      # https://stackoverflow.com/questions/43235179/how-to-execute-ssh-keygen-without-prompt#43235320
      - name: Generate a SSH key
        run: |
          set -x
          ssh-keygen -q -t rsa -N '' <<< ""$'\n'"y" 2>&1 >/dev/null
          ls -l /home/runner/.ssh/id_rsa

      - name: Install dependencies
        run: |
          sudo ./install.dependencies.sh

      #- name: Fix libvirtd confgiuration
      #  run: |
      #    echo "-- fix /etc/libvirt/libvirtd.conf"
      #    sudo sed -i 's/#unix_sock_group = "libvirt"/unix_sock_group = "docker"/g' /etc/libvirt/libvirtd.conf
      #    sudo sed -i 's/#unix_sock_ro_perms/unix_sock_ro_perms/g' /etc/libvirt/libvirtd.conf
      #    sudo sed -i 's/#unix_sock_rw_perms/unix_sock_rw_perms/g' /etc/libvirt/libvirtd.conf
      #    echo "-- grep /etc/libvirt/libvirtd.conf"
      #    grep "unix_sock_" /etc/libvirt/libvirtd.conf
      #    echo "-- restart service"
      #    sudo systemctl restart libvirtd.service --no-pager
      #    systemctl status libvirtd.service --no-pager
      #    systemctl status libvirtd-ro.socket --no-pager
      #    systemctl status libvirtd.socket --no-pager
      #    systemctl status libvirtd-admin.socket --no-pager

      - name: Checkout homecloud-ansible
        run: git checkout https://github.com/tmorin/homecloud-ansible.git

      - name: Run vagrant
        run: |
          sudo ./build.homecloud.sh
        working-directory: homecloud-ansible

      #- name: Run vagrant
      #  run: vagrant up
      #  working-directory: source
      #- name: Show guest
      #  run: vagrant ssh -c env
      #  working-directory: source
      #- name: Stop vagrant
      #  run: vagrant destroy --force
      #  working-directory: source
